### ISSUE TITLE
Problem add ac grundig 

### ISSUE THREAD

**Issue by home89c3** [rowysock/home-assistant-HomeWhiz#12] opened 2022-10-31 19:40 UTC
Hi, I try to connect an ac unit grundig grphi120 but after I added in hacs I try to add homewhiz integration, submit but nothing happens. Any suggestions please!

**Comment by TechHummel** [comment] 2022-11-23 08:00
Hi! Currently, only washing machines are supported 😢

**Comment by TechHummel** [comment] 2022-12-06 23:02
I'll close this for now since there hadn't been any updates. @home89c3, you can try again with the latest branch and we can look at this issue again if the problem is still there!

**Comment by home89c3** [comment] 2022-12-11 13:13
Hi sorry for the late reply. Ac is with WiFi not Bluetooth. This is the
label with the model. Any suggestion how can I integrate in home assistant.

**Comment by rowysock** [comment] 2022-12-12 09:02
@home89c3 in the latest beta release we added support for wifi devices via cloud. Can you test that?

**Comment by home89c3** [comment] 2022-12-17 11:47
@rowysock I install the new version and works to added my cloud account. Was detected my ac grundig automatically without modification on configuration.yaml.
I have the interne temperature, target, status if is on /off and the mode. All the information are like a sensor.
Thx for the new version
Do you think will be possible to controll the ac on, off and maybe the target themperature

**Comment by TechHummel** [comment] 2022-12-18 11:18
Glad it is working now!
What you are describing is already tracked with #53 , therefore I will close this issue 😄

**Closed by TechHummel** 2022-12-18 11:18 UTC
Labels: enhancement
