### ISSUE TITLE
Incorrect interpretation of time delay

### ISSUE THREAD

**Issue by maxx4096** [rowysock/home-assistant-HomeWhiz#33] opened 2022-12-01 12:20 UTC
Hi, I have a Beko b300 serie washing machine. Yesterday I noticed an absurdly large value for time delay, well over 8000 minutes.
I investigated a little and found that the time delay is correctly interpreted before you press the start button, after that it jumps to a big value.

For example, with a program length of 135 minutes and a delay of 4h displayed on the machine, the time delay in HA is 105. After pressing "start" the value jumps to 7913 and then decrease every minute before reaching a point where it change to unknown.
I missed the actual moment when it happened but I believe it is when the actual time remaining passes below 60 min. A program with a delay of 45min in HA, will go immediately to unknown when start is pressed. 
 
I can't help noticing a few bits in common between 105 and 7193...
 105   is 0000 0000 0110 1001b
7193 is 0001 1110 1110 1001b
1440 is 0000 0101 1010 0000b (24h, the max you can set on the machine)

Let me know if I can be of any help. 
Thank you for all the great work you've put in this

**Comment by rowysock** [comment] 2022-12-01 14:24
Can it be the same root cause as in #1, but for a different field?

**Comment by maxx4096** [comment] 2022-12-01 21:09
They are definitely doing something to the first byte of the message when the start button is pressed but it doesn't seems to be a simple bitmask. 128 was already handled in the code.
However, I've found a solution to the issue, see pr #35. Subtracting 7808 does the trick... 

This is the first time I do anything in python and I'm a noob with github, so, apologies in advance...

**Comment by TechHummel** [comment] 2022-12-01 21:58
No reason to apologise! PRs are always welcome 👍

**Comment by rowysock** [comment] 2022-12-01 22:43
@maxx4096 I think it's not an accident that 7808 = 128 * 61

**Comment by rowysock** [comment] 2022-12-06 09:37
Closed by @maxx4096 in #35

**Closed by rowysock** 2022-12-06 09:37 UTC
Labels: bug
