### ISSUE TITLE
Often the connection is lost

### ISSUE THREAD

**Issue by AlxVasilchenko** [rowysock/home-assistant-HomeWhiz#3] opened 2022-09-03 08:23 UTC
After a while, the values ​​freeze and are not displayed correctly, although the connection status is normal. 
Often the connection is lost and the values ​​are not displayed at all.  
I am using the BT Raspberry pi 3b and the  wsre7h636sbw Beko washing machine at distance of 5 meters. 
![Screenshot_2022-09-03-10-10-12-510_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/48676575/188262623-61a45adb-8572-4ff8-b842-3f73baba525f.jpg)
![IMG_20220903_101104.jpg](https://user-images.githubusercontent.com/48676575/188262630-54716715-3f7d-42d8-b603-162156e9b6d1.jpg)

**Comment by rowysock** [comment] 2022-09-04 12:34
You can enable logging for this integration by adding the following lines to your configuration.yaml

```
logger:
  logs:
    custom_components.HomeWhiz: debug
```
https://www.home-assistant.io/integrations/logger/

But, from the code perspective, there's not much anyone can do to make the connection more reliable. It's most probably a hardware issue.

**Comment by rowysock** [comment] 2022-09-19 20:47
Closing because the problem is most probably an unreliable connection, not the integration itself.

**Closed by rowysock** 2022-09-19 20:47 UTC
