### ISSUE TITLE
Device states again not translated after HA core update 

### ISSUE THREAD

**Issue by Mikescotland** [rowysock/home-assistant-HomeWhiz#119] opened 2023-04-09 09:59 UTC
Hey
Again my device states and options are strings not translated, happened after HA update.
Shows now for instance
DEVICE_STATE_OFF instead nice Off like it was before.

**Comment by TechHummel** [comment] 2023-04-09 10:59
We recently implemented some changes regarding translations of sensor states, but this has not been released yet.
Could you use the version from the main branch and check if the behaviour is different?

**Comment by Mikescotland** [comment] 2023-04-09 11:20
I think I'm using main branch (HACS downloaded)

**Comment by TechHummel** [comment] 2023-04-09 11:27
And you updated yesterday or today?

**Comment by Mikescotland** [comment] 2023-04-09 11:35
Updated once again now using "main". Same issue. States not translated.

**Comment by TechHummel** [comment] 2023-04-09 12:00
Thanks for the feedback, I'll have a look!

**Comment by macicek86** [comment] 2023-04-10 06:23
I reported same problem! After last update homeassistant.

**Comment by elektrolitr** [comment] 2023-04-12 04:58
![image](https://user-images.githubusercontent.com/121390684/230879714-8c0cf24d-fc70-460a-9a7f-1f6a6a5de943.png)

I can confirm that after HA Core update to 2023.4.2 some translations are lost. 
I didn't make any changes to Homewhiz plugin

I think the issue is related to HomeAssistant update

There are some possible clues in the "Validate with the hassfest" action: 
https://github.com/rowysock/home-assistant-HomeWhiz/actions/runs/4673575509

```
[validate](https://github.com/rowysock/home-assistant-HomeWhiz/actions/runs/4673575509/jobs/8276952033#step:9:253)
[TRANSLATIONS] Invalid sensor.en.json: Device class need to start with 'homewhiz__'. Key enum is invalid. See https://developers.home-assistant.io/docs/internationalization/core#stringssensorjson for dictionary value @ data['state']. Got {'enum': {'DEVICE_STATE_ON': 'On', 'DEVICE_STATE_OFF': 'Off', 'DEVICE_STATE_RUNNING': 'Running', 'DEVICE_STATE_PAUSED': 'Paused', 'DEVICE_STATE_TIME_DELAY_ACTIVE': 'Time Delay Active', 'PROGRAM_COTTONS': 'Cottons', 'PROGRAM_ECO_40_60': 'Eco 40-60', 'PROGRAM_SYNTHETICS': 'Synthetics', 'PROGRAM_MINI_MINI14': 'Xpress', 'PROGRAM_WOOL_HANDWASH': 'Woollens', 'PROGRAM_DELICATES': 'Delicates', 'PROGRAM_SPIN_PUMP': 'Spin+Drain', 'PROGRAM_RINSING': 'Rinse', 'PROGRAM_DARKWASH': 'Dark (Jeans)', 'PROGRAM_...

```
 
Below, there are some logs from HASS as well
Please pay attention that the 'device_class' for different sensors is stated as "enum"
If I understand correctly, the correct class shall be " homewhiz__state " or " homewhiz__dishwasher_state" or something similar and different for each sensor

```
2023-04-11 23:35:16.444 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [140574881282608] Sending 
[
{"id":2,"type":"event","event":{"a":{"sensor.dishwasher_state":{"s":"unavailable","a":{"options":["DEVICE_STATE_ON","DEVICE_STATE_OFF","DEVICE_STATE_RUNNING","DEVICE_STATE_PAUSED","DEVICE_STATE_CANCELLING","DEVICE_STATE_TIME_DELAY_ACTIVE","DEVICE_STATE_DOOR_OPEN","DEVICE_STATE_SETTINGS"],"device_class":"enum","friendly_name":"Dishwasher State"},"c":"01GXS0F9A388WH9STDQ2Q3QKG6","lc":1681245316.419281}}}},
{"id":2,"type":"event","event":{"a":{"sensor.dishwasher_programme":{"s":"unavailable","a":{"options":["PROGRAM_AUTO","PROGRAM_AQUA_FLEX","PROGRAM_INTENSIVE_70","PROGRAM_ECO_50","PROGRAM_DELICATE","PROGRAM_QUICK_AND_SHINE","PROGRAM_MINI","PROGRAM_PREWASH","PROGRAM_QUIET","PROGRAM_CLEAN_AND_SHINE","PROGRAM_INNERCLEAN"],"device_class":"enum","friendly_name":"Dishwasher Programme"},"c":"01GXS0F9A4G1WJRBV8H4KA875K","lc":1681245316.420165}}}},
{"id":2,"type":"event","event":{"a":{"sensor.dishwasher_sub_state":{"s":"unavailable","a":{"options":["DISHWASHER_MESSAGE_TIME_DELAY_STARTED","DISHWASHER_MESSAGE_PAUSED","DISHWASHER_MESSAGE_PAUSED","DISHWASHER_MESSAGE_PROGRAM_FINISHED","DISHWASHER_MESSAGE_TIME_DELAY_STARTED","DISHWASHER_MESSAGE_PROGRAM_SANITIZED","DISHWASHER_MESSAGE_CANCELLING","DISHWASHER_MESSAGE_TIME_DELAY_CANCELLED","DISHWASHER_MESSAGE_PROGRAM_STARTED","DISHWASHER_MESSAGE_WASHING","DISHWASHER_MESSAGE_RINSING","DISHWASHER_MESSAGE_DRYING"],"device_class":"enum","friendly_name":"Dishwasher Sub-state"},"c":"01GXS0F9A4RJXEAW856ZVDEFRF","lc":1681245316.420454}}}},
```

**Comment by elektrolitr** [comment] 2023-04-12 06:36
Ok, I'll correct myself 
SensorDeviceClass.ENUM shall be valid
https://github.com/rowysock/home-assistant-HomeWhiz/issues/37

**Comment by Mikescotland** [comment] 2023-04-14 15:51
Any news?

**Comment by TechHummel** [comment] 2023-04-14 16:42
Not from my side. Will try to take a look this weekend.

**Comment by TechHummel** [comment] 2023-04-17 21:20
Had a look, but not sure how to get translations working.
There is a [blog post](https://developers.home-assistant.io/docs/internationalization/core/#state-of-entities) saying that we should use a translation_key property, but our current translation method [still seems to be supported](https://developers.home-assistant.io/docs/internationalization/custom_integration).

**Comment by teqali** [comment] 2023-05-13 06:40
Any fix?

**Comment by teqali** [comment] 2023-06-03 02:03
My refrigerator broke down and was replaced with a new one. After adding the new refrigerator to the homewhiz application, it was added to the hacs/homwhiz application. However, my old devices still do not work.

**Comment by carawan** [comment] 2023-06-25 20:54
Hi,

The problem with the translation will not be solved?

**Comment by TechHummel** [comment] 2023-06-25 23:18
I will try to have a look in the next couple of weeks!

**Comment by Mikescotland** [comment] 2023-06-26 18:08
I made a workaround, just to have a proper values in the HA information.
For sensors which were of my interest, I created a template creating new sensors (they can't be use in the automations, use the original sensors) but for information dashboard they are fine. It's only for a washing mashine, but you get the idea...
![WashingM](https://github.com/rowysock/home-assistant-HomeWhiz/assets/52081323/9f0c56c6-a027-42bf-aa17-458b9ec29b8d)

I attach the template_sensors.yaml and don't forget to make an entry in your configuration.yaml:
template:
  - sensor: !include template_sensors.yaml

[template_sensors.zip](https://github.com/rowysock/home-assistant-HomeWhiz/files/11872365/template_sensors.zip)

**Comment by TechHummel** [comment] 2023-07-06 21:04
I think I am close to the solution 😃 
Managed to get select entities translated at last 🎉

**Comment by TechHummel** [comment] 2023-07-07 23:48
I think I fixed the translations 🥳 
Can you try the changes from #138 and report? 😄

**Comment by Mikescotland** [comment] 2023-07-12 13:14
Translations not fixed. Removed and re-added device

**Comment by TechHummel** [comment] 2023-07-12 13:37
How does it look like?

**Comment by carawan** [comment] 2023-07-12 13:51
I also removed HAСS and HomeWhiz, reinstalled. 
Switching HA to English or other languages, but alas, there is no translation ...
![Снимок экрана 2023-07-12 в 16 46 06](https://github.com/rowysock/home-assistant-HomeWhiz/assets/18556673/d7566c0b-d740-4831-94f4-97fe84a79baa)

**Comment by TechHummel** [comment] 2023-07-12 13:56
@Mikescotland @carawan The changes regarding the translations are not yet merged in the main branch.
Installing 0.4.0 installs an older version (even older than the main branch). 0.4.0 is also a fixed version and will never include any new changes. To test the translations, you would need to manually override the Homewhiz folder. However, I already received feedback and translations seem to work fine. So, as soon as @rowysock finds the time to merge this change and release a new version, translations should work again.

**Comment by carawan** [comment] 2023-07-13 08:16
Yes, indeed, I took the files from here https://github.com/rowysock/home-assistant-HomeWhiz/tree/fix_translations/custom_components/homewhiz/translations, created a Russian localization file and now everything works.
Thank you!

![Снимок экрана 2023-07-13 в 11 13 32](https://github.com/rowysock/home-assistant-HomeWhiz/assets/18556673/d874400c-6b84-4df2-a201-9d98354466c9)

**Comment by TechHummel** [comment] 2023-07-13 08:28
Is Russian officially supported by the Homewhiz app? If so, we could add the language to the translation script too.

**Comment by carawan** [comment] 2023-07-13 08:36
The Russian language is supported in the HomeWhiz application, at least in iOS I see it ...

![IMG_3211](https://github.com/rowysock/home-assistant-HomeWhiz/assets/18556673/9031b995-88e1-474e-a442-47b480aa8f08)

**Closed** 2023-07-13 12:50 UTC
Labels: bug

**Comment by teqali** [comment] 2023-07-21 21:18
the problem continues

**Comment by teqali** [comment] 2023-08-13 13:34
<img width="363" alt="Ekran Resmi 2023-08-13 16 29 51" src="https://github.com/rowysock/home-assistant-HomeWhiz/assets/78557513/ed1976cf-3470-4c06-b2ac-0e35f2ba10d4">
