### ISSUE TITLE
Error when i'm trying to connect HomeWhiz to HomeAssistant

### ISSUE THREAD

**Issue by CosminAndrei96** [rowysock/home-assistant-HomeWhiz#114] opened 2023-03-14 13:22 UTC
Hello, 

When i'm trying to integrate the HomeWhiz application in Home Assistant, i reached this errors:

Home Assistant Core
2023-03-14 15:02:37.901 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration homewhiz which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-14 15:13:42.655 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry AC for homewhiz
File "/config/custom_components/homewhiz/__init__.py", line 34, in async_setup_entry
File "/config/custom_components/homewhiz/__init__.py", line 77, in setup_cloud
File "/config/custom_components/homewhiz/__init__.py", line 72, in _lazy_install_awsiotsdk
homeassistant.requirements.RequirementsNotFound: Requirements for homewhiz not found: ['awsiotsdk'].

Can somebody help me?

**Comment by kkoouu** [comment] 2023-03-14 13:44
python3 -m pip install awsiotsdk

**Comment by TechHummel** [comment] 2023-03-14 14:57
@kkoouu Thanks for helping!
Also, this is a duplicate of #97, so I will close this 😊

**Closed by TechHummel** 2023-03-14 14:57 UTC
